# Generated by Django 5.1.3 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_checklist_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='checklists/'),
        ),
    ]
