# Generated by Django 5.1.3 on 2026-04-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_checklist_archive_item_fields_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['position', 'id']},
        ),
    ]
