# Generated by Django 5.1.3 on 2026-04-25 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_checklistitem_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sort_direction',
            field=models.CharField(default='asc', max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sort_option',
            field=models.CharField(default='position', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark'), ('contrast', 'High Contrast')], default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='checklist.tag'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='unique_tag_per_user'),
        ),
    ]
