# Generated by Django 5.1.3 on 2026-04-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_checklistitem_completed_at_checklistitem_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
